/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4_GPIO.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#endif

void delay(){
	for (uint32_t i=0;i<200000;i++);
}

//int main(void)
//{
//	GPIO_Handle_t LED_PIN;
//	LED_PIN.pGPIOx=GPIOA;
//	LED_PIN.GPIO_Config.GPIO_PinNumber=GPIO_PIN_6;
//	LED_PIN.GPIO_Config.GPIO_PinMode=GPIO_OUT;
//	LED_PIN.GPIO_Config.GPIO_PinSpeed=GPIO_SPEED_FAST;
//	LED_PIN.GPIO_Config.GPIO_PinOPType=GPIO_OP_PP;
//	LED_PIN.GPIO_Config.GPIO_PinControl=GPIO_NO_PUPD;
//	GPIO_Init(&LED_PIN);
//
//    /* Loop forever */
//	while(1){
//		GPIO_Toggle(GPIOA, GPIO_PIN_6);
//		delay();
//	}
//}
